export const INSTRUMENTS = {
    piano: {
        id: 'piano',
        name: 'Piano',
        displayName: 'Piano',
        icon: '🎹',
        category: 'keyboard',
        notes: ['C', 'C#', 'D', 'D#', 'E', 'F', 'F#', 'G', 'G#', 'A', 'A#', 'B'],
        octaves: [2, 3, 4, 5, 6],
        defaultOctave: 4,
        hasChords: false,
        hasPads: false,
        color: '#6200ee',
    },
    guitar: {
        id: 'guitar',
        name: 'guitar',
        displayName: 'Guitar',
        icon: '🎸',
        category: 'strings',
        chords: ['C', 'D', 'E', 'F', 'G', 'A', 'B', 'Cm', 'Dm', 'Em', 'Fm', 'Gm', 'Am', 'Bm'],
        strings: 6,
        hasChords: true,
        hasPads: false,
        color: '#03dac6',
    },
    bass: {
        id: 'bass',
        name: 'bass',
        displayName: 'Bass Guitar',
        icon: '🎸',
        category: 'strings',
        notes: ['E', 'F', 'F#', 'G', 'G#', 'A', 'A#', 'B', 'C', 'C#', 'D', 'D#'],
        octaves: [1, 2, 3],
        defaultOctave: 2,
        strings: 4,
        hasChords: false,
        hasPads: false,
        color: '#bb86fc',
    },
    drums: {
        id: 'drums',
        name: 'drums',
        displayName: 'Drums',
        icon: '🥁',
        category: 'percussion',
        pads: [
            { id: 'kick', label: 'Kick', note: 'C1', color: '#ff4444' },
            { id: 'snare', label: 'Snare', note: 'D1', color: '#44ff44' },
            { id: 'hihat', label: 'Hi-Hat', note: 'F#1', color: '#4444ff' },
            { id: 'tom1', label: 'Tom 1', note: 'A1', color: '#ffaa44' },
            { id: 'tom2', label: 'Tom 2', note: 'G1', color: '#ff44aa' },
            { id: 'crash', label: 'Crash', note: 'C#2', color: '#44aaff' },
            { id: 'ride', label: 'Ride', note: 'D#2', color: '#aaff44' },
        ],
        hasChords: false,
        hasPads: true,
        color: '#cf6679',
    },
    synth: {
        id: 'synth',
        name: 'synth',
        displayName: 'Synthesizer',
        icon: '🎛️',
        category: 'keyboard',
        notes: ['C', 'C#', 'D', 'D#', 'E', 'F', 'F#', 'G', 'G#', 'A', 'A#', 'B'],
        octaves: [2, 3, 4, 5, 6],
        defaultOctave: 4,
        waveforms: ['sine', 'square', 'sawtooth', 'triangle'],
        defaultWaveform: 'sawtooth',
        hasChords: false,
        hasPads: false,
        color: '#018786',
    },
    violin: {
        id: 'violin',
        name: 'violin',
        displayName: 'Violin',
        icon: '🎻',
        category: 'strings',
        notes: ['G', 'G#', 'A', 'A#', 'B', 'C', 'C#', 'D', 'D#', 'E', 'F', 'F#'],
        octaves: [3, 4, 5, 6],
        defaultOctave: 4,
        strings: 4,
        hasChords: false,
        hasPads: false,
        color: '#b00020',
    },
    flute: {
        id: 'flute',
        name: 'flute',
        displayName: 'Flute',
        icon: '🪈',
        category: 'wind',
        notes: ['C', 'C#', 'D', 'D#', 'E', 'F', 'F#', 'G', 'G#', 'A', 'A#', 'B'],
        octaves: [4, 5, 6],
        defaultOctave: 5,
        hasChords: false,
        hasPads: false,
        color: '#3700b3',
    },
    tabla: {
        id: 'tabla',
        name: 'tabla',
        displayName: 'Tabla',
        icon: '🪘',
        category: 'percussion',
        pads: [
            { id: 'dha', label: 'Dha', note: 'C2', color: '#ff6b6b' },
            { id: 'dhin', label: 'Dhin', note: 'D2', color: '#4ecdc4' },
            { id: 'tin', label: 'Tin', note: 'E2', color: '#45b7d1' },
            { id: 'na', label: 'Na', note: 'F2', color: '#f7b731' },
        ],
        hasChords: false,
        hasPads: true,
        color: '#e67e22',
    },
    dholak: {
        id: 'dholak',
        name: 'dholak',
        displayName: 'Dholak',
        icon: '🥁',
        category: 'percussion',
        pads: [
            { id: 'dha', label: 'Dha', note: 'C2', color: '#e74c3c' },
            { id: 'ge', label: 'Ge', note: 'D2', color: '#3498db' },
            { id: 'ka', label: 'Ka', note: 'E2', color: '#2ecc71' },
        ],
        hasChords: false,
        hasPads: true,
        color: '#d35400',
    },
    trumpet: {
        id: 'trumpet',
        name: 'trumpet',
        displayName: 'Trumpet',
        icon: '🎺',
        category: 'wind',
        notes: ['C', 'C#', 'D', 'D#', 'E', 'F', 'F#', 'G', 'G#', 'A', 'A#', 'B'],
        octaves: [3, 4, 5],
        defaultOctave: 4,
        hasChords: false,
        hasPads: false,
        color: '#ff9800',
    },
    saxophone: {
        id: 'saxophone',
        name: 'saxophone',
        displayName: 'Saxophone',
        icon: '🎷',
        category: 'wind',
        notes: ['C', 'C#', 'D', 'D#', 'E', 'F', 'F#', 'G', 'G#', 'A', 'A#', 'B'],
        octaves: [3, 4, 5],
        defaultOctave: 4,
        hasChords: false,
        hasPads: false,
        color: '#ffc107',
    },
    world: {
        id: 'world',
        name: 'world',
        displayName: 'World Percussion',
        icon: '🌍',
        category: 'percussion',
        pads: [
            { id: '1', label: 'Conga High', note: 'C4', color: '#8d6e63' },
            { id: '2', label: 'Conga Low', note: 'C3', color: '#795548' },
            { id: '3', label: 'Bongo High', note: 'D4', color: '#a1887f' },
            { id: '4', label: 'Bongo Low', note: 'D3', color: '#8d6e63' },
        ],
        hasChords: false,
        hasPads: true,
        color: '#4caf50',
    },
};

// Get all instrument IDs
export const INSTRUMENT_IDS = Object.keys(INSTRUMENTS);

// Get instruments by category
export const getInstrumentsByCategory = (category) => {
    return Object.values(INSTRUMENTS).filter(inst => inst.category === category);
};

// Get instrument config by ID
export const getInstrumentConfig = (id) => {
    return INSTRUMENTS[id] || null;
};

// Check if instrument has specific feature
export const instrumentHasFeature = (id, feature) => {
    const config = getInstrumentConfig(id);
    return config ? config[feature] === true : false;
};
